apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Namespace }}
    {{- if .Values.istio.enabled }}
    istio-injection: enabled
    {{- end }}
    helm.sh/chart: {{ include "ai-orchestrator.chart" . }}
    app.kubernetes.io/name: {{ include "ai-orchestrator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}