groups:
  - name: system_alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}"

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 10% on {{ $labels.instance }} mount {{ $labels.mountpoint }}"

  - name: application_alerts
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "{{ $labels.job }} service is down for more than 1 minute"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for {{ $labels.job }} service"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time"
          description: "95th percentile response time is above 1 second for {{ $labels.job }}"

      - alert: WorkflowExecutionFailureRate
        expr: rate(workflow_executions_total{status="failed"}[5m]) / rate(workflow_executions_total[5m]) * 100 > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High workflow execution failure rate"
          description: "Workflow execution failure rate is above 10% for the last 5 minutes"

      - alert: QueueBacklog
        expr: execution_queue_size > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Execution queue backlog"
          description: "Execution queue has more than 100 pending items for 5 minutes"

  - name: database_alerts
    rules:
      - alert: DatabaseConnectionsHigh
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "Database connections are above 80% of max connections"

      - alert: DatabaseSlowQueries
        expr: rate(pg_stat_database_tup_returned[5m]) / rate(pg_stat_database_tup_fetched[5m]) < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Database slow queries detected"
          description: "Database query efficiency is below 10%"

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Redis memory usage high"
          description: "Redis memory usage is above 90%"

  - name: business_metrics_alerts
    rules:
      - alert: LowUserActivity
        expr: rate(user_logins_total[1h]) < 10
        for: 30m
        labels:
          severity: info
        annotations:
          summary: "Low user activity"
          description: "User login rate is below 10 per hour for 30 minutes"

      - alert: WorkflowCreationDrop
        expr: rate(workflows_created_total[1h]) < 5
        for: 1h
        labels:
          severity: info
        annotations:
          summary: "Workflow creation rate dropped"
          description: "Workflow creation rate is below 5 per hour"

      - alert: ExecutionVolumeSpike
        expr: rate(workflow_executions_total[5m]) > 100
        for: 5m
        labels:
          severity: info
        annotations:
          summary: "High execution volume"
          description: "Workflow execution rate is above 100 per 5 minutes"