apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-service
  namespace: ai-orchestrator
  labels:
    app: monitoring-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-service
      version: v1
  template:
    metadata:
      labels:
        app: monitoring-service
        version: v1
    spec:
      containers:
      - name: monitoring-service
        image: ai-orchestrator/monitoring-service:latest
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: MONITORING_SERVICE_PORT
        - name: ELASTICSEARCH_HOST
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: ELASTICSEARCH_HOST
        - name: ELASTICSEARCH_PORT
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: ELASTICSEARCH_PORT
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: REDIS_PORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: ai-orchestrator
  labels:
    app: monitoring-service
spec:
  selector:
    app: monitoring-service
  ports:
  - port: 3005
    targetPort: 3005
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: monitoring-service-hpa
  namespace: ai-orchestrator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: monitoring-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80