apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestration-service
  namespace: ai-orchestrator
  labels:
    app: orchestration-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orchestration-service
      version: v1
  template:
    metadata:
      labels:
        app: orchestration-service
        version: v1
    spec:
      containers:
      - name: orchestration-service
        image: ai-orchestrator/orchestration-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: ORCHESTRATION_SERVICE_PORT
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ai-orchestrator-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ai-orchestrator-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: REDIS_PORT
        - name: LANGFLOW_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-orchestrator-secrets
              key: LANGFLOW_API_KEY
        - name: N8N_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-orchestrator-secrets
              key: N8N_API_KEY
        - name: LANGSMITH_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-orchestrator-secrets
              key: LANGSMITH_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: orchestration-service
  namespace: ai-orchestrator
  labels:
    app: orchestration-service
spec:
  selector:
    app: orchestration-service
  ports:
  - port: 3002
    targetPort: 3002
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orchestration-service-hpa
  namespace: ai-orchestrator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orchestration-service
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80