apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-service
  namespace: ai-orchestrator
  labels:
    app: workflow-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workflow-service
      version: v1
  template:
    metadata:
      labels:
        app: workflow-service
        version: v1
    spec:
      containers:
      - name: workflow-service
        image: ai-orchestrator/workflow-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: WORKFLOW_SERVICE_PORT
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ai-orchestrator-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ai-orchestrator-secrets
              key: POSTGRES_PASSWORD
        - name: ELASTICSEARCH_HOST
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: ELASTICSEARCH_HOST
        - name: ELASTICSEARCH_PORT
          valueFrom:
            configMapKeyRef:
              name: ai-orchestrator-config
              key: ELASTICSEARCH_PORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: file-storage
          mountPath: /app/storage
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: file-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-service
  namespace: ai-orchestrator
  labels:
    app: workflow-service
spec:
  selector:
    app: workflow-service
  ports:
  - port: 3003
    targetPort: 3003
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: workflow-service-hpa
  namespace: ai-orchestrator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workflow-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80